### ISSUE TITLE
General code resilience improvements via syscall fuzzing

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#239]
## Description

For example, malloc/callco/realloc returns a pointer to new memory when it can, and `NULL` when it can't. When you use librnp over CLI it will works fine, but when you're using it as part as service the syscall may return `NULL` and SEGFAULT or data corruption may happened.

So, we can dramatically increase quality of RNP code and catch issues like this: https://github.com/riboseinc/rnp/pull/223/commits/d521d6d554f1735a304707cecf3789504ffd13b4 — it happened because EXPAND_ARRAY calls calloc and nobody checks a `calloc`'s output.

We can use riboseinc/retrace#125 for this, which @catap will work on.

## Steps to Reproduce

https://github.com/riboseinc/rnp/pull/223/commits/d521d6d554f1735a304707cecf3789504ffd13b4 type patches are needed to catch `calloc` failures.

## Expected Behavior

Crashes, dumps and leaks should not occur regardless of what is given.

## Actual Behavior

rnp code routines need to be more solid.

## Steps
 - [x] Implemented memory fuzzing on retrace:  https://github.com/riboseinc/retrace/issues/156
 - [x] Run rnp with memory fuzzing and fix bugs here and at botat: https://github.com/riboseinc/rnp/pull/255 https://github.com/randombit/botan/pull/1095 https://github.com/randombit/botan/pull/1097
 - [x]  Implement io fuzzing on retrace: https://github.com/riboseinc/retrace/issues/141
 - [x] Run rnp with io fuzzing and fix bugs here and at botan https://github.com/riboseinc/retrace/pull/188 https://github.com/riboseinc/retrace/issues/189 https://github.com/riboseinc/retrace/pull/194 https://github.com/riboseinc/rnp/pull/268
 - [x] Fix memory leaks: fixed as https://github.com/riboseinc/rnp/pull/259 and proposed https://github.com/riboseinc/rnp/issues/260

**Comment by catap** [comment]
First part is here: https://github.com/riboseinc/rnp/pull/255

**Comment by catap** [comment]
BTW I'm blocked by botan.
@randombit right now I've blocked because botan throws a `std:bad_alloc` exception for example from [here](https://github.com/randombit/botan/blob/master/src/lib/ffi/ffi.cpp#L528)

I think the best way is catch it on botan-side  and returns error in C-like way because rnp is written on C.

**Comment by dewyatt** [comment]
@catap @randombit I went ahead and filed a PR that will hopefully fix that issue: https://github.com/randombit/botan/pull/1095

**Comment by ronaldtse** [comment]
@dewyatt I finally found out your middle name is "Fast" 😉

**Comment by dewyatt** [comment]
@ronaldtse haha! I was waiting on something large to compile so I needed a distraction.

**Comment by catap** [comment]
And one more fix inside botan: https://github.com/randombit/botan/pull/1097

**Comment by catap** [comment]
Status update.

1,000 iterations passed of rnp_test with retrace-config
```
logtofile,/dev/null
memoryfuzzing,0.001
```

So, results.

rnp changed:
```
27 files changed, 935 insertions(+), 465 deletions(-)
```
bottan changed:
```
35 files changed, 468 insertions(+), 133 deletions(-)
```

Trying a longer one with 10,000 iteration.

**Comment by catap** [comment]
Status update: tests passed!

For history, used config:
```
logtofile,/dev/null,0
fuzzingseed,12345
incompleteio,16
```

**Comment by catap** [comment]
@ronaldtse I did it at 10,000 times and it works :) So, I think I can close the issue.

**Comment by ronaldtse** [comment]
Thanks @catap !
